const MAX_COMMENTS = 5;
const MAX_DESCRIPTION_SIZE = 140;
const FILMS_CARDS_COUNT = 20;
const EXTRA_FILMS_CARDS_COUNT = 2;
const FILMS_PER_STEP = 5;

export {
  MAX_COMMENTS,
  MAX_DESCRIPTION_SIZE,
  FILMS_CARDS_COUNT,
  FILMS_PER_STEP,
  EXTRA_FILMS_CARDS_COUNT
};
